config/routes.rb
Rails.application.routes.draw do
  resources :cats
  root 'pages#main'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  enum gender: [ :female, :male ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :gender, :home)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.number_field :gender %>
  </div>
  <div class="field">
    <%= f.label :home %><br>
    <%= f.check_box :home %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Home</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.gender %></td>
        <td><%= cat.home %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @cat.gender %>
</p>

<p>
  <strong>Home:</strong>
  <%= @cat.home %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Etusivu', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Lahjoita', root_path%></li>
    </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
<li> <%= link_to 'Kotia etsivät eläimet', root_path%> </li>
<li> <%= link_to 'Kodin saaneet', root_path%> </li>
<li> <%= link_to 'Tue toimintaa', root_path%> </li>
<li> <%= link_to 'Ajankohtaista', root_path%> </li>
<li> <%= link_to 'Yhdistys', root_path%> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Animalshelter" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Animalshelter" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  </head>
  <body>

    <div class="topdiv">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 id="organization_title">Kodinvaihtajat Ry</h1>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <p id="slogan"> Eläinystävän asialla. </p>
          </div>
        </div>
      </div>
    </div>

    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <img id="main_img" src="../../assets/kissajakoira2.jpg">

    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>

    <footer>
      <div class="container small">

        <div class="row">
          <div class="col-md-2">
            <div class="col-md-12 text-muted">
              ELÄIMESTÄ LUOPUMASSA?
            </div>
            <div class="col-md-12">
              Yhdeydenottolomake
            </div>
            <div class="col-md-12">
              Toimintatapojamme
            </div>
          </div>

          <div class="col-md-2">
            <div class="col-md-12 text-muted">
              KOTIA ETSIVÄT ELÄIMET
            </div>
            <div class="col-md-12">
              Kissat
            </div>
            <div class="col-md-12">
              Koirat
            </div>
            <div class="col-md-12">
              Muut eläimet
            </div>
          </div>

          <div class="col-md-2">
            <div class="col-md-12 text-muted">
              KODIN SAANEET
            </div>
            <div class="col-md-12">
              2016
            </div>
            <div class="col-md-12">
              2015
            </div>
            <div class="col-md-12">
              2014
            </div>
            <div class="col-md-12">
              2010 - 2013
            </div>
          </div>

          <div class="col-md-2">
            <div class="col-md-12 text-muted">
              MITEN VOIT AUTTAA
            </div>
            <div class="col-md-12">
              Ryhdy eläimen kotihoitajaksi
            </div>
            <div class="col-md-12">
              Jaa esitteitä
            </div>
            <div class="col-md-12">
              Liity jäseneksi
            </div>
            <div class="col-md-12">
              Anna eläimelle koti
            </div>
          </div>

          <div class="col-md-2">
            <div class="col-md-12 text-muted">
              AJANKOHTAISTA
            </div>
            <div class="col-md-12">
              Päivitykset
            </div>
            <div class="col-md-12">
              Uutisia
            </div>
            <div class="col-md-12">
              Media
            </div>
          </div>

          <div class="col-md-2">
              <div class="col-md-12 text-muted">
                  YHDISTYKSEN TILI
              </div>
              <div class="col-md-12">
                Kodinvaihtajat ry
              </div>
              <div class="col-md-12">
                FI42 8146 9710 0177 07
              </div>
          </div>


        </div>

        <div class="row">
          <div class="col-md-12 text-center">
            <a class="btn-facebook">
              <span class="fa fa-facebook-official"></span> Kodinvaihtajat Facebookissa
            </a>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
              <p class="text-center"> Copyright &copy; Satu Häkkinen </p>
          </div>
        </div>

      </div>
    </footer>

  </body>
</html>

app/views/pages/main.html.erb
<div id="firstBox" class="row">
  <div class="container">
    <div class="col-md-3">
      <h3 class="text-right">Löydä uusi ystäväsi</h3>
    </div>
    <div class="col-md-9">
      <p>Kodinvaihtajat Ry perustettiin 3.1.2010 auttamaan uutta kotia etsivien lemmikki- ja kotieläinten uudelleensijoituksessa.
        Yhdistys toimii vapaaehtoisvoimin toimialueenaan koko Suomi.
        Linkkejä seuraamalla löydät lisää tietoa yhdistyksestä sekä toiminnastamme. Mikäli ne eivät tarjoa vastausta kysymyksiisi,
        otathan meihin yhteyttä! </p>
    </div>
  </div>
</div>

<div id="secondBox" class="row">
    <div class="container">
      <div class="col-md-3">
        <h3 class="text-right">Haluatko auttaa?</h3>
      </div>
      <div class="col-md-9">
        <p> Yhdistyksemme toimii vapaaehtoisvoimin. Auttaa voi liittymällä jäseneksi, adoptoimalla eläimen,
        tarjoamalla apua eläinten kuljetuksissa, toimimana sijaiskotina ja levittämällä tietoa yhdistyksestä.
        Rahalahjoituksella tuet yhdistystämme eläinten eläinlääkäri- ja ruokakuluissa.
        Mikäli haluaisit osallistua toimintaamme tavalla tai toisella, täytäthän yhteydenottolomakkeen!</p>
      </div>
    </div>
</div>

<div id="thirdBox" class="row">
  <div class="container">
    <div class="col-md-3">
      <h3 class="text-right">Me etsimme kotia</h3>
    </div>
      <div class="col-md-3">
        <img src="../../assets/koditon1.jpg" alt="..." class="img-rounded img-responsive" >
      </div>
      <div class="col-md-3">
        <img src="../../assets/koditon4.jpg" alt="..." class="img-rounded img-responsive" >
      </div>
      <div class="col-md-3">
        <img src="../../assets/koditon3.jpg" alt="..." class="img-rounded img-responsive" >
      </div>
  </div>
</div>